### ISSUE TITLE
Help on Usage...

### ISSUE THREAD

**Issue by SpecNext** [mikedailly/SDCardEditor#1]
Dear Mike,

how can I understand this:
===== Snip =====
Usage
Example :- loading a ZX Spectrum Next image
SDCard card = SDCard.Open( "C:\source\ZXSpectrum\_Demos\2gbimage\cspect-next-2gb.img" );  
List<DirectoryEntry> dir = card.ReadDirectory("Demos\\WidescreenImageDemo");  
byte[] f = card.LoadFile("demos\\WidescreenImageDemo\\readme.txt");  
===== Snap =====
I´m on Windows. Are these commandline-parameters for SDCardEditor.exe or should these go into a config-File? Or is this for Usage calling the .NET DLL?

Regards

**Comment by mikedailly** [comment]
This code is if you're using the C# DLL for your own project. 

You'll notice there are 2 sections, the "access" dll, and the SD Card Editor.  This code is for using the Access DLL in your own C# project.

If you want to open an SD card in the GUI, then just run the .EXE and type the full path into the "SD Card Image" text box, then click open. For some reason you can't cut/paste text into that text box - I've not fixed that yet, nor added a file browser.... sorry.
You can't drag files IN at the moment, just out.

**Comment by SpecNext** [comment]
Thank you very much for your clarification!
